### ISSUE TITLE
Not working for jupyter lab?

### ISSUE THREAD

**Issue by ajing** [alexanderkuk/log-progress#14]
When I run the code in jupyter lab. I got this print out:

```
VBox(children=(HTML(value=''), IntProgress(value=0, max=2)))
```

**Comment by mneira10** [comment]
I can confirm its not working in jupyter lab

**Comment by mneira10** [comment]
You can fix the issue by installing the widgets with the jupyterlab extension:

jupyter labextension install @jupyter-widgets/jupyterlab-manager

https://github.com/jupyterlab/jupyterlab/issues/3925

**Comment by ajing** [comment]
@mneira10 I was having some problem with that solution. But after I do `jupyter lab clean` and then the solution works.
