### ISSUE TITLE
license

### ISSUE THREAD

**Issue by lurgyman63** [alexanderkuk/log-progress#6]
Soon I hope to release an instrument control library that I've been working on. It will include some basic jupyter notebook capability. The log_progress code here would be an ideal type of indicator for that use.

Could you post a LICENSE file so that I can redistribute (with credit of course), or to clarify that I cannot?

**Comment by alexanderkuk** [comment]
Done https://github.com/alexanderkuk/log-progress/blob/master/LICENSE
